# Generated by Django 5.0.1 on 2024-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('natureza', models.CharField(max_length=255)),
                ('dt_movimento', models.DateField()),
                ('dt_vencimento', models.DateField()),
                ('centro_de_custo', models.CharField(max_length=255)),
                ('movimentacao', models.CharField(max_length=255)),
                ('conta', models.CharField(max_length=255)),
                ('cartao', models.CharField(max_length=255)),
                ('status_movimento', models.CharField(max_length=255)),
                ('forma_pagamento', models.CharField(max_length=255)),
                ('qtde_parcela', models.IntegerField()),
                ('parcela', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
